# Generated by Django 5.1.5 on 2025-01-20 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chai_type', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KI', 'KIWI'), ('EL', 'ELAICHI'), ('PL', 'PLAIN')], max_length=2)),
            ],
        ),
    ]
