# Generated by Django 5.2.4 on 2025-07-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
